apiVersion: v1
kind: Secret
metadata:
  namespace: mongodb-namespace
  name: my-secret-mongodb
  labels:
    app: mongodb
    tier: backend
type: Opaque
data: 
   username: c2F5ZWRhdHdoLTIy
   password: c2F5ZWQyMDA1