apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-sc
  labels:
    app: mongodb
    tier: backend
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode:  WaitForFirstConsumer